//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace _04EF.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class tStudent
    {
        [DisplayName("學號")]
        [Required(ErrorMessage ="學號是必填欄位哦!")]
        [RegularExpression("^[I-S][0-5][0-9]{2}$", ErrorMessage = "學號格式錯誤了O_O")]      //^=開始、$=結束
        public string fStuId { get; set; }

        [DisplayName("姓名")]
        [Required(ErrorMessage = "姓名是必填欄位哦!")]
        public string fName { get; set; }

        [DisplayName("信箱")]
        [EmailAddress(ErrorMessage ="信箱格式錯誤了O_O")]
        public string fEmail { get; set; }

        [DisplayName("成績")]
        [Range(0,100,ErrorMessage ="請輸入0~100的分數")]
        public Nullable<int> fScore { get; set; }
    }
}
